version: '2'

services:
    domainhealth-monitor:
        build: 
          context: ./
          dockerfile: Dockerfile

        env_file:
         - .env

        environment:
          VIRTUAL_HOST: ${HOSTNAMES}
          VIRTUAL_PORT: 80
          VIRTUAL_PROTO: http
          LETSENCRYPT_HOST: ${HOSTNAMES}
          LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}


#        ports:
#          - "${EXTERNAL_PORT}:22"


        volumes:
          - /tmp/.domainhealth-www:/usr/share/nginx/html/
          - ./index.html:/usr/share/nginx/html/index.html:ro



networks:
  default:
    external:
      name: nginx-proxy

